image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [603.05908,   2.01865, 962.32883,
           0.     , 604.17475, 555.80814,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.214470, 0.226404, -0.670503, 0.591651]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [603.05908,   2.01865, 962.32883,   0.     ,
           0.     , 604.17475, 555.80814,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
