camerakiri:
  camera_node:
    ros__parameters:
      video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:4:1.0-video-index0
      camera_info_url: "package://ode_bringup/config/calibration.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [1920,1080]

cameratengah:
  camera_node:
    ros__parameters:
      video_device: /dev/video2
      # video_device: /dev/v4l/by-path/pci-0000:05:00.3-usb-0:1.1:1.0-video-index0
      # video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:5:1.0-video-index0
      camera_info_url: "package://ode_bringup/config/ost.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [1920,1080]

camerakanan:
  camera_node:
    ros__parameters:
      video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:2:1.0-video-index0 
      camera_info_url: "package://ode_bringup/config/calibration.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [1920,1080]