velodynekanan:
  velodyne_driver_node:
    ros__parameters:
      device_ip: 192.168.1.201
      gps_time: false
      time_offset: 0.0
      enabled: true
      read_once: false
      read_fast: false
      repeat_delay: 0.0
      frame_id: velodynekanan
      model: VLP16
      rpm: 600.0
      port: 2368
      timestamp_first_packet: false

  velodyne_transform_node:
    ros__parameters:
        calibration: VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true



velodynetengah:
  velodyne_driver_node:
    ros__parameters:
      device_ip: 192.168.1.202
      gps_time: false
      time_offset: 0.0
      enabled: true
      read_once: false
      read_fast: false
      repeat_delay: 0.0
      frame_id: velodynetengah
      model: VLP16
      rpm: 600.0
      port: 2370
      timestamp_first_packet: false

  velodyne_transform_node:
    ros__parameters:
        calibration: VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true


velodynekiri:
  velodyne_driver_node:
    ros__parameters:
      device_ip: 192.168.1.203
      gps_time: false
      time_offset: 0.0
      enabled: true
      read_once: false
      read_fast: false
      repeat_delay: 0.0
      frame_id: velodynekiri
      model: VLP16
      rpm: 600.0
      port: 2370
      timestamp_first_packet: false
      
  velodyne_transform_node:
    ros__parameters:
        calibration: VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true